name = "electricpmr"
main = "cloudflare/worker.ts"
compatibility_date = "2025-04-29"

[[d1_databases]]
binding = "DB"
database_name = "electricpmr"
database_id = "9aeea559-27c5-4684-a5aa-1883beb65750"

[[r2_buckets]]
binding = "WORK_EXAMPLES_BUCKET"
bucket_name = "electricpmr-work-examples"

[vars]
APP_BASE_URL = "http://127.0.0.1:8787"
SESSION_TTL_DAYS = "30"
